require('settings.coc')
require('settings.misc')
-- require('settings.lualine')
require('settings.indent-line')
require('settings.bufferline')
require('settings.nvim-tree')
require('settings.gitsigns')
require('settings.transparent')
