require('settings.apperaence')
require('settings.lualine')
require('settings.indent-line')
require('settings.bufferline')
require('settings.nvim-tree')
require('settings.gitsigns')
require('settings.transparent')
require('settings.treesitter')
require('settings.neovide')
require('settings.comment')
require('settings.telescope')
require('settings.nvim-web-devicons')
require('settings.todo-comments')
require('settings.lsp-config')
require('settings.symbols-outline')
require('settings.code-action-menu')
-- require('settings.noice')
